import { Employee } from './employee.model';

export const MOCK_EMPLOYEES: Employee[] = [
  {
    id: '1',
    firstName: 'Elena',
    lastName: 'Cruz',
    email: 'elena.cruz@shiftmate.com',
    phone: '+1 (555) 123-4567',
    employeeId: 'EMP-001',
    department: 'Engineering',
    position: 'Software Developer',
    dateJoined: '2025-01-15',
    status: 'Active',
  },
  {
    id: '2',
    firstName: 'Marcus',
    lastName: 'Santos',
    email: 'marcus.santos@shiftmate.com',
    phone: '+1 (555) 234-5678',
    employeeId: 'EMP-002',
    department: 'Human Resources',
    position: 'HR Specialist',
    dateJoined: '2025-02-02',
    status: 'Active',
  },
  {
    id: '3',
    firstName: 'Sofia',
    lastName: 'Reyes',
    email: 'sofia.reyes@shiftmate.com',
    phone: '+1 (555) 345-6789',
    employeeId: 'EMP-003',
    department: 'Finance',
    position: 'Accountant',
    dateJoined: '2025-03-18',
    status: 'On Leave',
  },
  {
    id: '4',
    firstName: 'Daniel',
    lastName: 'Garcia',
    email: 'daniel.garcia@shiftmate.com',
    phone: '+1 (555) 456-7890',
    employeeId: 'EMP-004',
    department: 'Operations',
    position: 'Operations Manager',
    dateJoined: '2024-04-10',
    status: 'Active',
  },
  {
    id: '5',
    firstName: 'Chloe',
    lastName: 'Chen',
    email: 'chloe.chen@shiftmate.com',
    phone: '+1 (555) 567-8901',
    employeeId: 'EMP-005',
    department: 'Engineering',
    position: 'Frontend Engineer',
    dateJoined: '2024-11-20',
    status: 'Active',
  },
  {
    id: '6',
    firstName: 'Liam',
    lastName: 'Wilson',
    email: 'liam.wilson@shiftmate.com',
    phone: '+1 (555) 678-9012',
    employeeId: 'EMP-006',
    department: 'Finance',
    position: 'Financial Analyst',
    dateJoined: '2023-08-05',
    status: 'Inactive',
  }
];
